terms:
- id: https://libraries.indiana.edu/music
  term: William & Gayle Cook Music Library
  address: 200 South Jordan Ave, Bloomington IN, 47405
  phone_number: (812) 855-2970
  contact_email: libmus@indiana.edu
  gfa_pickup: PW
  staff_only: false
  pickup_location: true
  digital_location: true
  url: https://libraries.indiana.edu/music
  library:
    label: William & Gayle Gook Music Library
    code: libmus
- id: https://www.ius.edu/library/
  term: IU Southeast Library
  address: 4201 Grant Line Road, New Albany, IN 47150
  phone_number: (812) 941-2489
  contact_email: libmus@ius.edu
  gfa_pickup: PW
  staff_only: false
  pickup_location: true
  digital_location: true
  url: https://www.ius.edu/library/
  library:
    label: IU Southeast Library
    code: libius
- id: https://libraries.indiana.edu/alf-services
  term: Ruth Lilly Auxiliary Library Facility
  address: 851 North Range Road
  phone_number: (812) 856-0832
  contact_email: libalf@indiana.edu
  gfa_pickup: PW
  staff_only: false
  pickup_location: true
  digital_location: true
  url: https://libraries.indiana.edu/alf-services
  library:
    label: Ruth Lilly Auxiliary Library Facility
    code: libalf
- id: https://libraries.indiana.edu/wells
  term: Herman B Wells Library
  address: 1320 East Tenth Street
  phone_number: (812) 855-0100
  contact_email: libref@indiana.edu
  gfa_pickup: PW
  staff_only: false
  pickup_location: true
  digital_location: true
  url: https://libraries.indiana.edu/wells
  library:
    label: Herman B Wells Library
    code: libref
- id: https://libraries.indiana.edu/lilly-library
  term: Lilly Library
  address: 1200 East Seventh Street
  phone_number: (812) 855-2452
  contact_email: liblilly@indiana.edu
  gfa_pickup: PW
  staff_only: false
  pickup_location: true
  digital_location: true
  url: https://libraries.indiana.edu/lilly-library
  library:
    label: Lilly Library
    code: liblilly
